### ISSUE TITLE
json vs jsonb

### ISSUE THREAD

**Issue by domiko** [kaleidos/grails-postgresql-extensions#59]
Hi guys,
Thanks for a great plugin.

I've tried re-mapping a gorm field from json to jsonb.
However, pgAdmin still lists the field as json (not jsonb).

Regards

**Comment by lmivan** [comment]
Hi.

I think that hibernate is not capable of modifying the column type even if you have set your `DataSource.groovy` `dbCreate` property to `update`.

You can always modify the type of the column using pgAdmin or psql:

```sql
ALTER TABLE my_table ALTER COLUMN my_column_of_type_json TYPE jsonb USING my_column_of_type_json::jsonb;
```

Please note that the `USING` clause is necessary because postgresql doesn't know how to convert directly from json to jsonb.

I hope this helps.

**Comment by domiko** [comment]
Thank Ivan for your very quick reply.
Your tip works like a charm.

Thanks,
Dominique

**Comment by lmivan** [comment]
Great! :-)
